/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import Mathlib.Algebra.BigOperators.Fin
public import Mathlib.Algebra.DualNumber
public import Mathlib.Algebra.RingQuot
public import Mathlib.Data.ZMod.Basic
public import Mathlib.LinearAlgebra.TensorAlgebra.Basic

@[expose] public section

/-!
# Milnor K-theory of a field modulo `ℓ`, symbols and symbol length

Milnor [Milnor1970] defined the graded ring $K^M_*(F)$ of a field $F$ as the quotient of the
tensor algebra of the abelian group $F^\times$, written additively, by the two-sided ideal
generated by the elements $\{a\} \otimes \{b\}$ with $a + b = 1$ (the Steinberg relations).
This file defines:

* `MilnorK F ℓ`: the ring $K^M_*(F)/\ell$, the quotient of `TensorAlgebra ℤ (Additive Fˣ)` by
  the Steinberg relations and the relation `ℓ = 0`. For `ℓ = 0` it is $K^M_*(F)$ itself;
* `MilnorK.of ℓ a`: the class $\{a\}$ of a unit `a`;
* `MilnorK.symbol ℓ a`: the symbol $\{a_1, \dots, a_n\} = \{a_1\} \cdots \{a_n\}$ of an
  `n`-tuple of units;
* `MilnorK.grade F ℓ n`: the degree-`n` part $K^M_n(F)/\ell$, the additive subgroup generated
  by the symbols of degree `n`;
* `MilnorK.symbolLengthBounds F ℓ n`: the set of `m` such that every element of
  $K^M_n(F)/\ell$ is a sum of at most `m` symbols. Its least element, when it exists, is the
  *symbol length* of $K^M_n(F)/\ell$ [Krashen2024, §2.1.3.4].
* `MilnorK.augmentation F ℓ`: the augmentation $K^M_*(F)/\ell \to \mathbb{Z}/\ell$, which
  shows that `MilnorK F ℓ` is nontrivial for `ℓ ≠ 1` (`MilnorK.nontrivial`);
* `MilnorK.toDualNumber F ℓ φ`: the map to the dual numbers $(\mathbb{Z}/\ell)[\varepsilon]$
  attached to a homomorphism $\varphi \colon F^\times \to \mathbb{Z}/\ell$. It detects degree
  one, so the Steinberg relations do not collapse $K^M_1(F)/\ell$ (`MilnorK.of_ne_zero`,
  `MilnorK.grade_one_ne_bot`). It says nothing about the degrees `≥ 2`, where the symbol length
  problem lives.

In degree `0` the symbols are all equal to the empty product `1`, so $K^M_0(F)/\ell = \mathbb{Z}/\ell$
has symbol length `ℓ - 1` for `ℓ ≥ 1` (`MilnorK.isLeast_symbolLengthBounds_zero`). In degree `1`
every class is a single symbol, so the symbol length of $K^M_1(F)/\ell$ is at most `1`
(`MilnorK.one_mem_symbolLengthBounds_one`), with equality as soon as the group is nonzero
(`MilnorK.isLeast_symbolLengthBounds_one`).

The defining ideal is homogeneous, so the degree-`n` part of the quotient is the image of the
degree-`n` part of the tensor algebra, which is spanned by the symbols. No numeric symbol
length is defined, so that no convention is needed when `symbolLengthBounds F ℓ n` is empty.

## References

* [Milnor1970] J. Milnor, *Algebraic K-theory and quadratic forms*, Invent. Math. 9 (1970),
  318–344, [doi:10.1007/BF01425486](https://doi.org/10.1007/BF01425486).
* [Krashen2024] D. Krashen, *PCMI Summer School (not quite) notes*, notes for the minicourse
  *Field arithmetic and the complexity of algebraic objects*, PCMI Graduate Summer School on
  Motivic Homotopy Theory, 2024, draft of 24 July 2024,
  [pdf](https://www.ias.edu/sites/default/files/pcmi-2024-07-24%20krashen.pdf).
-/

open TensorAlgebra

variable (F : Type*) [Field F]

namespace MilnorK

/-- The relations defining `K^M_*(F)/ℓ` as a quotient of the tensor algebra of `Fˣ`: the
Steinberg relation `{a}{b} = 0` when `a + b = 1`, and the relation `ℓ = 0`. -/
inductive Rel (ℓ : ℕ) : TensorAlgebra ℤ (Additive Fˣ) → TensorAlgebra ℤ (Additive Fˣ) → Prop
  | steinberg (a b : Fˣ) (h : (a : F) + (b : F) = 1) :
      Rel ℓ (ι ℤ (Additive.ofMul a) * ι ℤ (Additive.ofMul b)) 0
  | natCast : Rel ℓ (ℓ : TensorAlgebra ℤ (Additive Fˣ)) 0

end MilnorK

/-- The Milnor K-ring `K^M_*(F)/ℓ` of the field `F` with coefficients in `ℤ/ℓ`. For `ℓ = 0`
this is the Milnor K-ring `K^M_*(F)`. -/
abbrev MilnorK (ℓ : ℕ) := RingQuot (MilnorK.Rel F ℓ)

namespace MilnorK

variable {F} (ℓ : ℕ)

/-- The class `{a}` of a unit `a` in `K^M_1(F)/ℓ`. -/
def of (a : Fˣ) : MilnorK F ℓ := RingQuot.mkRingHom (Rel F ℓ) (ι ℤ (Additive.ofMul a))

@[simp]
theorem of_one : of ℓ (1 : Fˣ) = 0 := by
  simp [of]

@[simp]
theorem of_mul (a b : Fˣ) : of ℓ (a * b) = of ℓ a + of ℓ b := by
  simp [of]

@[simp]
theorem of_inv (a : Fˣ) : of ℓ a⁻¹ = -of ℓ a := by
  simp [of]

@[simp]
theorem of_pow (a : Fˣ) (k : ℕ) : of ℓ (a ^ k) = k • of ℓ a := by
  induction k with
  | zero => simp
  | succ k ih => rw [pow_succ, of_mul, ih, succ_nsmul]

/-- The class map `{·} : Fˣ → K^M_1(F)/ℓ` as an additive homomorphism. -/
def ofHom : Additive Fˣ →+ MilnorK F ℓ where
  toFun a := of ℓ a.toMul
  map_zero' := by simp
  map_add' a b := by simp [of_mul]

@[simp]
theorem ofHom_apply (a : Additive Fˣ) : ofHom ℓ a = of ℓ a.toMul := rfl

/-- The Steinberg relation `{a}{b} = 0` when `a + b = 1`. -/
theorem of_mul_of_eq_zero (a b : Fˣ) (h : (a : F) + (b : F) = 1) : of ℓ a * of ℓ b = 0 := by
  rw [of, of, ← map_mul, RingQuot.mkRingHom_rel (Rel.steinberg a b h), map_zero]

/-- The relation `ℓ = 0` in `K^M_*(F)/ℓ`. -/
@[simp]
theorem natCast_eq_zero : (ℓ : MilnorK F ℓ) = 0 := by
  rw [← map_natCast (RingQuot.mkRingHom (Rel F ℓ)),
    RingQuot.mkRingHom_rel (Rel.natCast (F := F) (ℓ := ℓ)), map_zero]

/-- The symbol `{a 0, …, a (n - 1)} = {a 0} ⋯ {a (n - 1)}` of an `n`-tuple of units. -/
def symbol {n : ℕ} (a : Fin n → Fˣ) : MilnorK F ℓ := (List.ofFn fun i ↦ of ℓ (a i)).prod

@[simp]
theorem symbol_zero (a : Fin 0 → Fˣ) : symbol ℓ a = 1 := by
  simp [symbol]

theorem symbol_succ {n : ℕ} (a : Fin (n + 1) → Fˣ) :
    symbol ℓ a = of ℓ (a 0) * symbol ℓ (fun i ↦ a i.succ) := by
  simp [symbol, List.ofFn_succ]

@[simp]
theorem symbol_one (a : Fin 1 → Fˣ) : symbol ℓ a = of ℓ (a 0) := by
  simp [symbol_succ]

theorem symbol_pair (a b : Fˣ) : symbol ℓ ![a, b] = of ℓ a * of ℓ b := by
  simp [symbol_succ]

/-- The Steinberg relation `{a, b} = 0` when `a + b = 1`. -/
theorem symbol_pair_eq_zero (a b : Fˣ) (h : (a : F) + (b : F) = 1) : symbol ℓ ![a, b] = 0 := by
  rw [symbol_pair, of_mul_of_eq_zero ℓ a b h]

variable (F)

/-- The degree-`n` part `K^M_n(F)/ℓ` of `K^M_*(F)/ℓ`: the additive subgroup generated by the
symbols of degree `n`. -/
def grade (n : ℕ) : AddSubgroup (MilnorK F ℓ) :=
  AddSubgroup.closure (Set.range (symbol ℓ : (Fin n → Fˣ) → MilnorK F ℓ))

theorem symbol_mem_grade {n : ℕ} (a : Fin n → Fˣ) : symbol ℓ a ∈ grade F ℓ n :=
  AddSubgroup.subset_closure ⟨a, rfl⟩

/-- The set of `m` such that every element of `K^M_n(F)/ℓ` is a sum of at most `m` symbols.
Its least element, when it exists, is the symbol length of `K^M_n(F)/ℓ`. -/
def symbolLengthBounds (n : ℕ) : Set ℕ :=
  {m | ∀ x ∈ grade F ℓ n, ∃ k ≤ m, ∃ s : Fin k → Fin n → Fˣ, x = ∑ i, symbol ℓ (s i)}

theorem mem_symbolLengthBounds_of_le {m m' n : ℕ} (h : m ∈ symbolLengthBounds F ℓ n)
    (hm : m ≤ m') : m' ∈ symbolLengthBounds F ℓ n :=
  fun x hx ↦ let ⟨k, hk, s, hs⟩ := h x hx; ⟨k, hk.trans hm, s, hs⟩

theorem zero_mem_symbolLengthBounds_iff {n : ℕ} :
    0 ∈ symbolLengthBounds F ℓ n ↔ grade F ℓ n = ⊥ := by
  constructor
  · intro h
    rw [eq_bot_iff]
    intro x hx
    obtain ⟨k, hk, s, rfl⟩ := h x hx
    obtain rfl : k = 0 := Nat.le_zero.mp hk
    simp
  · intro h x hx
    rw [h, AddSubgroup.mem_bot] at hx
    exact ⟨0, le_rfl, Fin.elim0, by simp [hx]⟩

/-- If every unit of `F` is an `ℓ`-th power, then `K^M_n(F)/ℓ = 0` for `n ≥ 1`. -/
theorem grade_eq_bot_of_forall_exists_pow_eq (h : ∀ a : Fˣ, ∃ b : Fˣ, b ^ ℓ = a) {n : ℕ}
    (hn : n ≠ 0) : grade F ℓ n = ⊥ := by
  rw [eq_bot_iff, grade, AddSubgroup.closure_le]
  rintro _ ⟨a, rfl⟩
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_one_of_ne_zero hn
  obtain ⟨b, hb⟩ := h (a 0)
  rw [SetLike.mem_coe, AddSubgroup.mem_bot, symbol_succ, ← hb, of_pow, nsmul_eq_mul,
    natCast_eq_zero, zero_mul, zero_mul]

/-- The augmentation `K^M_*(F)/ℓ → ℤ/ℓ`, which sends every class `{a}` to `0`. -/
def augmentation : MilnorK F ℓ →+* ZMod ℓ :=
  RingQuot.lift ⟨(TensorAlgebra.lift ℤ (0 : Additive Fˣ →ₗ[ℤ] ZMod ℓ)).toRingHom, by
    intro x y h
    cases h with
    | steinberg a b h => simp
    | natCast => simp⟩

@[simp]
theorem augmentation_of (a : Fˣ) : augmentation F ℓ (of ℓ a) = 0 := by
  simp [augmentation, of, RingQuot.lift_mkRingHom_apply]

/-- `K^M_*(F)/ℓ` is nontrivial for `ℓ ≠ 1`, since the augmentation maps it onto `ℤ/ℓ`. -/
theorem nontrivial (hℓ : ℓ ≠ 1) : Nontrivial (MilnorK F ℓ) := by
  have : Nontrivial (ZMod ℓ) := by
    obtain _ | _ | k := ℓ
    · exact ZMod.nontrivial'
    · exact absurd rfl hℓ
    · have : Fact (1 < k + 2) := ⟨by omega⟩
      infer_instance
  exact (augmentation F ℓ).domain_nontrivial

/-- The empty symbol is `1`, so `1 ∈ K^M_0(F)/ℓ`. -/
theorem one_mem_grade_zero : (1 : MilnorK F ℓ) ∈ grade F ℓ 0 := by
  simpa using symbol_mem_grade F ℓ (Fin.elim0 : Fin 0 → Fˣ)

/-- `K^M_0(F)/ℓ = ℤ/ℓ` is generated by the empty symbol `1`. -/
theorem mem_grade_zero_iff {x : MilnorK F ℓ} : x ∈ grade F ℓ 0 ↔ ∃ z : ℤ, (z : MilnorK F ℓ) = x := by
  simp [grade, Set.range_unique, AddSubgroup.mem_closure_singleton]

/-- Every bound on the symbol length of `K^M_0(F)/ℓ = ℤ/ℓ` is at least `ℓ - 1`: the augmentation
sends a sum of `j` empty symbols to `j`, so the class of `ℓ - 1` needs at least `ℓ - 1` symbols. -/
theorem sub_one_le_of_mem_symbolLengthBounds_zero {k : ℕ} (hℓ : 0 < ℓ)
    (hk : k ∈ symbolLengthBounds F ℓ 0) : ℓ - 1 ≤ k := by
  have hx : ((ℓ - 1 : ℕ) : MilnorK F ℓ) ∈ grade F ℓ 0 := by
    simpa using (grade F ℓ 0).nsmul_mem (one_mem_grade_zero F ℓ) (ℓ - 1)
  obtain ⟨j, hj, s, hs⟩ := hk _ hx
  have heq : ((ℓ - 1 : ℕ) : ZMod ℓ) = (j : ZMod ℓ) := by
    simpa using congrArg (augmentation F ℓ) hs
  by_contra h
  have := congrArg ZMod.val heq
  rw [ZMod.val_natCast_of_lt (by omega), ZMod.val_natCast_of_lt (by omega)] at this
  omega

/-- Every element of `K^M_0(F)/ℓ = ℤ/ℓ` is a sum of at most `ℓ - 1` empty symbols. -/
theorem sub_one_mem_symbolLengthBounds_zero (hℓ : 0 < ℓ) : ℓ - 1 ∈ symbolLengthBounds F ℓ 0 := by
  intro x hx
  obtain ⟨z, rfl⟩ := (mem_grade_zero_iff F ℓ).mp hx
  have hℓ' : (ℓ : ℤ) ≠ 0 := by omega
  refine ⟨(z % ℓ).toNat, ?_, fun _ ↦ Fin.elim0, ?_⟩
  · have := Int.emod_lt_of_pos z (by omega : (0 : ℤ) < ℓ)
    omega
  · calc (z : MilnorK F ℓ) = ((z % ℓ : ℤ) : MilnorK F ℓ) := by
          simp [Int.emod_def, natCast_eq_zero]
      _ = ((((z % ℓ).toNat : ℕ) : ℤ) : MilnorK F ℓ) := by
          rw [Int.toNat_of_nonneg (Int.emod_nonneg z hℓ')]
      _ = (((z % ℓ).toNat : ℕ) : MilnorK F ℓ) := Int.cast_natCast _
      _ = ∑ _i : Fin (z % ℓ).toNat, symbol ℓ (Fin.elim0 : Fin 0 → Fˣ) := by simp

/-- For `ℓ ≥ 1`, the symbol length of `K^M_0(F)/ℓ = ℤ/ℓ` is `ℓ - 1`. -/
theorem isLeast_symbolLengthBounds_zero (hℓ : 0 < ℓ) :
    IsLeast (symbolLengthBounds F ℓ 0) (ℓ - 1) :=
  ⟨sub_one_mem_symbolLengthBounds_zero F ℓ hℓ,
    fun _ hk ↦ sub_one_le_of_mem_symbolLengthBounds_zero F ℓ hℓ hk⟩

/-! ### Degree one

Degree one is completely understood: every class of `K^M_1(F)/ℓ` is a single symbol, and the
dual-number map below shows that `K^M_1(F)/ℓ` is nonzero as soon as some homomorphism
`Fˣ → ℤ/ℓ` is. So the symbol length question in degree `1` is not vacuous. Degrees `≥ 2` get no
such certificate here: that `K^M_n(F)/ℓ ≠ 0` for `n ≥ 2` needs genuine input, such as a
nontrivial division algebra for `n = 2`. -/

/-- The map to the dual numbers `(ℤ/ℓ)[ε]` attached to a homomorphism `φ : Fˣ → ℤ/ℓ`: it sends
`{a}` to `φ(a) ε` and kills every product of two classes of degree one, so in particular it
kills the Steinberg relations. -/
noncomputable def toDualNumber (φ : Additive Fˣ →+ ZMod ℓ) :
    MilnorK F ℓ →+* DualNumber (ZMod ℓ) :=
  RingQuot.lift ⟨(TensorAlgebra.lift ℤ
      ((TrivSqZeroExt.inrHom (ZMod ℓ) (ZMod ℓ)).restrictScalars ℤ ∘ₗ
        φ.toIntLinearMap)).toRingHom, by
    intro x y h
    cases h with
    | steinberg a b _ => simp
    | natCast =>
        refine (TrivSqZeroExt.ext ?_ ?_).trans (map_zero _).symm <;>
          simp [TrivSqZeroExt.fst_natCast, TrivSqZeroExt.snd_natCast]⟩

@[simp]
theorem toDualNumber_of (φ : Additive Fˣ →+ ZMod ℓ) (a : Fˣ) :
    toDualNumber F ℓ φ (of ℓ a) = TrivSqZeroExt.inr (φ (Additive.ofMul a)) := by
  simp [toDualNumber, of, RingQuot.lift_mkRingHom_apply]

/-- Degree one does not collapse: if a homomorphism `φ : Fˣ → ℤ/ℓ` is nonzero on `a`, then the
class `{a}` is nonzero in `K^M_1(F)/ℓ`. -/
theorem of_ne_zero (φ : Additive Fˣ →+ ZMod ℓ) (a : Fˣ)
    (hφ : φ (Additive.ofMul a) ≠ 0) : of ℓ a ≠ 0 :=
  fun h ↦ hφ (by simpa using congrArg (fun x ↦ (toDualNumber F ℓ φ x).snd) h)

/-- `K^M_1(F)/ℓ ≠ 0` whenever some homomorphism `φ : Fˣ → ℤ/ℓ` is nonzero. -/
theorem grade_one_ne_bot (φ : Additive Fˣ →+ ZMod ℓ) (a : Fˣ)
    (hφ : φ (Additive.ofMul a) ≠ 0) : grade F ℓ 1 ≠ ⊥ := by
  intro h
  refine of_ne_zero F ℓ φ a hφ ?_
  have ha := symbol_mem_grade F ℓ (fun _ ↦ a : Fin 1 → Fˣ)
  rw [h, AddSubgroup.mem_bot] at ha
  simpa using ha

/-- `K^M_1(F)/ℓ` is the image of `Fˣ`, since sums and negatives of degree-one symbols are again
degree-one symbols. -/
theorem grade_one : grade F ℓ 1 = (ofHom (F := F) ℓ).range := by
  refine le_antisymm ?_ ?_
  · rw [grade, AddSubgroup.closure_le]
    rintro _ ⟨s, rfl⟩
    exact ⟨Additive.ofMul (s 0), by simp⟩
  · rintro _ ⟨a, rfl⟩
    simpa using symbol_mem_grade F ℓ (fun _ ↦ a.toMul : Fin 1 → Fˣ)

/-- Every class in `K^M_1(F)/ℓ` is a single symbol. -/
theorem one_mem_symbolLengthBounds_one : 1 ∈ symbolLengthBounds F ℓ 1 := by
  intro x hx
  obtain ⟨a, rfl⟩ := (grade_one F ℓ).le hx
  exact ⟨1, le_rfl, fun _ _ ↦ a.toMul, by simp⟩

/-- `0` is not a bound for the symbol length in degree `1` when `K^M_1(F)/ℓ ≠ 0`. -/
theorem zero_notMem_symbolLengthBounds_one (h : grade F ℓ 1 ≠ ⊥) :
    0 ∉ symbolLengthBounds F ℓ 1 :=
  fun hk ↦ h ((zero_mem_symbolLengthBounds_iff F ℓ).mp hk)

/-- The symbol length of `K^M_1(F)/ℓ` is `1` as soon as the group is nonzero. Use
`MilnorK.grade_one_ne_bot` to get the hypothesis from a homomorphism `Fˣ → ℤ/ℓ`. -/
theorem isLeast_symbolLengthBounds_one (h : grade F ℓ 1 ≠ ⊥) :
    IsLeast (symbolLengthBounds F ℓ 1) 1 :=
  ⟨one_mem_symbolLengthBounds_one F ℓ, fun _ hk ↦ Nat.one_le_iff_ne_zero.mpr fun hk0 ↦
    zero_notMem_symbolLengthBounds_one F ℓ h (hk0 ▸ hk)⟩

end MilnorK
