/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesUtil

/-!
# The Eisenbud-Green-Harris conjecture

Let $S = k[x_1, \dots, x_n]$ with $x_1 > x_2 > \dots > x_n$ and let $I \subseteq S$ be a
homogeneous ideal. The *Hilbert function* of $I$ is $d \mapsto \dim_k I_d$.

A *monomial ideal* is an ideal generated by monomials. A monomial ideal $L$ is *lex* if for any
two monomials $u, v$ of the same degree with $u >_{\mathrm{lex}} v$ we have $u \in L$ whenever
$v \in L$. Macaulay's theorem says that every homogeneous ideal has the same Hilbert function as
a unique lex ideal.

**Eisenbud-Green-Harris conjecture.** If $I$ contains a regular sequence of forms of degrees
$d_1 \le \dots \le d_c$, then there is a lex ideal $L$ such that $I$ has the same Hilbert
function as $L + (x_1^{d_1}, \dots, x_c^{d_c})$.

Eisenbud, Green and Harris proposed the conjecture in [EGH93] and [EGH96] to generalise a
theorem of Castelnuovo and Cayley-Bacharach type theorems for zero-dimensional subschemes of
$\mathbb P^m$. It refines Macaulay's theorem, which is the case $c = 0$.

The conjecture is open in general. It holds when the regular sequence is monomial, by the
Clements-Lindström theorem [CL69], and when the degrees grow quickly, namely when
$d_i \ge \sum_{j < i} (d_j - 1)$ for all $i \ge 3$: this is due to Caviglia and De Stefani
[CDS20], improving on Caviglia and Maclagan [CM08], who assumed the strict inequality. Other
known cases are $c \le 2$, and $d_1 = \dots = d_c = 2$ with $c \le 5$ by Güntürkün and
Hochster; [CDS20] lists these with references.

The Lex-plus-powers conjecture, attributed to Charalambous and Evans, predicts that the ideal
$L + (x_1^{d_1}, \dots, x_c^{d_c})$ above also has the largest graded Betti numbers among all
ideals with that Hilbert function containing a regular sequence in those degrees. The
Eisenbud-Green-Harris conjecture is its $i = 0$ case [CS18]. It is not formalised here.

The Hilbert function `MvPolynomial.hilbertFunction`, lex ideals `MvPolynomial.IsLexIdeal` and the
ideal of pure powers `MvPolynomial.purePowersIdeal` are defined in
`FormalConjecturesForMathlib.RingTheory.MvPolynomial.LexPlusPowers`.

*References:*
- [EGH93] D. Eisenbud, M. Green, J. Harris, *Higher Castelnuovo theory*, in Journées de Géométrie
  Algébrique d'Orsay, Astérisque 218 (1993), 187-202.
- [EGH96] D. Eisenbud, M. Green, J. Harris, *Cayley-Bacharach theorems and conjectures*, Bull.
  Amer. Math. Soc. 33 (1996), 295-324.
  [PDF](https://www.ams.org/journals/bull/1996-33-03/S0273-0979-96-00666-0/S0273-0979-96-00666-0.pdf)
- [CS18] G. Caviglia, A. Sammartano, *On the Lex-plus-powers conjecture*, Adv. Math. 340 (2018),
  1148-1163. [arXiv:1802.03035](https://arxiv.org/abs/1802.03035), Conjecture 1.1.
- [CDS20] G. Caviglia, A. De Stefani, *The Eisenbud-Green-Harris conjecture for fast-growing
  degree sequences*, Trans. Amer. Math. Soc. 375 (2022), 2777-2792.
  [arXiv:2007.15467](https://arxiv.org/abs/2007.15467), Definition 2.1, Conjecture 2.3 and
  Theorem A. The statement formalised below is Conjecture 2.3.
- [CM08] G. Caviglia, D. Maclagan, *Some cases of the Eisenbud-Green-Harris conjecture*, Math.
  Res. Lett. 15 (2008), 427-433.
- [CL69] G. F. Clements, B. Lindström, *A generalization of a combinatorial theorem of Macaulay*,
  J. Combin. Theory 7 (1969), 230-238.
- [FR12] C. A. Francisco, B. P. Richert, *Lex-plus-powers ideals*, in Syzygies and Hilbert
  functions, Lect. Notes Pure Appl. Math. 254, 113-144.
  [PDF](https://math.okstate.edu/people/chris/lpp-updated-final.pdf)
-/

@[expose] public section

open MvPolynomial

namespace EisenbudGreenHarris

attribute [local instance] MvPolynomial.gradedAlgebra

variable {n : ℕ} {k : Type*} [Field k]

/--
**The Eisenbud-Green-Harris conjecture.** Let $I \subseteq k[x_1, \dots, x_n]$ be a homogeneous
ideal containing a regular sequence of forms of degrees $d_1 \le \dots \le d_c$. Then there is a
lex ideal $L$ such that $I$ has the same Hilbert function as $L + (x_1^{d_1}, \dots, x_c^{d_c})$.
-/
@[category research open, AMS 13]
theorem eisenbud_green_harris {c : ℕ} (hc : c ≤ n) (d : Fin c → ℕ) (hd : Monotone d)
    (I : Ideal (MvPolynomial (Fin n) k))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) k))
    (f : Fin c → MvPolynomial (Fin n) k) (hfd : ∀ i, (f i).IsHomogeneous (d i))
    (hfI : ∀ i, f i ∈ I)
    (hf : RingTheory.Sequence.IsRegular (MvPolynomial (Fin n) k) (List.ofFn f)) :
    ∃ L : Ideal (MvPolynomial (Fin n) k), IsLexIdeal L ∧
      ∀ e, hilbertFunction I e = hilbertFunction (L + purePowersIdeal hc d) e := by
  sorry

/--
**Macaulay's theorem**: every homogeneous ideal has the same Hilbert function as a lex ideal.
This is the case $c = 0$ of `eisenbud_green_harris`, where the ideal of pure powers is zero
(`MvPolynomial.purePowersIdeal_zero`).
-/
@[category research solved, AMS 13]
theorem eisenbud_green_harris.variants.macaulay (I : Ideal (MvPolynomial (Fin n) k))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) k)) :
    ∃ L : Ideal (MvPolynomial (Fin n) k), IsLexIdeal L ∧
      ∀ e, hilbertFunction I e = hilbertFunction L e := by
  sorry

/--
**The Clements-Lindström theorem** [CL69]: the conjecture holds for an ideal that already
contains the pure powers $x_1^{d_1}, \dots, x_c^{d_c}$.
-/
@[category research solved, AMS 13]
theorem eisenbud_green_harris.variants.clements_lindstrom {c : ℕ} (hc : c ≤ n) (d : Fin c → ℕ)
    (hd : Monotone d) (I : Ideal (MvPolynomial (Fin n) k))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) k)) (hIp : purePowersIdeal hc d ≤ I) :
    ∃ L : Ideal (MvPolynomial (Fin n) k), IsLexIdeal L ∧
      ∀ e, hilbertFunction I e = hilbertFunction (L + purePowersIdeal hc d) e := by
  sorry

/--
The conjecture holds when the degrees grow quickly enough, namely when
$d_i \ge \sum_{j < i} (d_j - 1)$ for all $i \ge 3$. This is [CDS20, Theorem A]; Caviglia and
Maclagan [CM08] had proved it under the strict inequality. Indices here are `0`-based, so
$i \ge 3$ becomes `2 ≤ i`. The subtraction is on `ℕ`, which is harmless because a regular
sequence of degrees `d` forces `1 ≤ d j`.
-/
@[category research solved, AMS 13]
theorem eisenbud_green_harris.variants.caviglia_deStefani {c : ℕ} (hc : c ≤ n) (d : Fin c → ℕ)
    (hd : Monotone d) (hgrow : ∀ i : Fin c, 2 ≤ (i : ℕ) → ∑ j ∈ Finset.Iio i, (d j - 1) ≤ d i)
    (I : Ideal (MvPolynomial (Fin n) k))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) k))
    (f : Fin c → MvPolynomial (Fin n) k) (hfd : ∀ i, (f i).IsHomogeneous (d i))
    (hfI : ∀ i, f i ∈ I)
    (hf : RingTheory.Sequence.IsRegular (MvPolynomial (Fin n) k) (List.ofFn f)) :
    ∃ L : Ideal (MvPolynomial (Fin n) k), IsLexIdeal L ∧
      ∀ e, hilbertFunction I e = hilbertFunction (L + purePowersIdeal hc d) e := by
  sorry

end EisenbudGreenHarris
